[package]
name = "interactive_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
serde = "1.0.130"
serde_json = "1.0.67"
dialoguer = "0.9.0"

